### ISSUE TITLE
Fall 2019 Task List

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/ram_pump#88]
- [ ] fix summer report
- [x] Procoda  and Method file setup with PID
- [ ] finalize experimental setup (pressuring air chamber)
- [ ] better protocol to adjust nut (currently small adjustment makes BIG difference)
- [x] theoretical volume of water pumped per cycle (current based on hydrostatics)
- [x] ideal velocity vs. time graph

**Comment by ChingPangggg** [comment]
define efficiency as the ideal conditions including force
pid code data averaging input pressure first

**Comment by ChingPangggg** [comment]
pressurize the airchamber by allowing water to be pumped up pass union in the air chamber first and then turn on the pump to pressurize it

**Comment by ChingPangggg** [comment]
1. Talk to Paul about possibilities of installing ram pump integrated into work station (by Oct 9)
2. CAD design of new design (by Sept 27) (including hydraulic calculations for pipe size and tank size)
3. Figure the parts needed in new design (Mcmaster if can find everything, can also go to US plastics, order parts asap) (by Oct 2)
4. Build parts (by Oct 9)
